### ISSUE TITLE
Problem with FFI

### ISSUE THREAD

**Issue by levraipixel** [dryade/georuby-ext#2]
Hi there,

Your gem seems really nice, and I would like to be able to use it for my project. I've been using georuby for a while but I need to compute an interseection between to polygons.
My problem is that I cannot manage to use your gem: 

``` ruby
require 'georuby-ext'
-> LoadError: library names list must not be empty
-> from /home/yann/.rvm/gems/ruby-2.0.0-p247/gems/ffi-1.9.0/lib/ffi/library.rb:87:in `ffi_lib'
```

Could you help ? That would be really wonderful !

Best,

Yann

**Comment by ldonnet** [comment]
Hi Yann,

Have you look at the travis file (https://github.com/dryade/georuby-ext/blob/master/.travis.yml)? 
You must have installed this packages on Debian/Ubuntu system : 

``` shell
before_install:
  - sudo apt-get update
  - sudo apt-get install libproj-dev libgeos-dev libffi-dev libsparsehash-dev
```

Best Regards
Luc

**Comment by levraipixel** [comment]
Thanks, @ldonnet, that helped.
Now I'm inside Rails and it appears that your gem is not Rails 4-compatible due to the dependency `s.add_dependency "activesupport", "<= 3.2.13"` you put in your gemspec.
I have tried to remove it from your gemspec and it works fine: maybe you should relax that dependency ?
Same remark about all other dependencies: why force such precise versions ?
Best,

Yann

**Comment by ldonnet** [comment]
I should have a look to this dependencies problem. I'm not the only user for this project, I ask my teammates and answer you.

Best
Luc

**Comment by levraipixel** [comment]
thanks a lot, that would be great.

**Comment by ldonnet** [comment]
I make some improvements to test all the ruby version and Rails version together.
So I relax the dependency on active support now.
I make some tests and release sooner a new gem version.

**Comment by levraipixel** [comment]
thanks !
